# Generated by Django 4.0.4 on 2022-05-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('semestre', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('ECTS', models.PositiveIntegerField()),
                ('anoletivo', models.PositiveIntegerField()),
                ('topicos', models.CharField(max_length=500)),
                ('ranking', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
