# Generated by Django 4.0.4 on 2022-05-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='professores',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='topicos',
            field=models.TextField(max_length=500),
        ),
    ]
