# Generated by Django 4.0.4 on 2022-05-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cadeira_professores_alter_cadeira_topicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pagina',
            field=models.URLField(default=''),
        ),
    ]
