# Generated by Django 4.0.4 on 2022-05-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='tipo',
            field=models.CharField(choices=[('Primario', 'Primario'), ('Basico', 'Basico'), ('Secundario', 'Secundario'), ('Superior', 'Superior')], default='', max_length=50),
        ),
    ]
