# Generated by Django 4.0.4 on 2022-05-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_linguagem_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(to='portfolio.projeto'),
        ),
    ]
