# Generated by Django 4.0.4 on 2022-05-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_cadeira_projetos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='professores',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professoresDasPraticas',
            field=models.ManyToManyField(related_name='praticas', to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professoresTeoricas',
            field=models.ManyToManyField(related_name='teoricas', to='portfolio.pessoa'),
        ),
    ]
