# Generated by Django 4.0.4 on 2022-05-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_tecnologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='tipo',
            field=models.CharField(choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End')], default='', max_length=50),
        ),
    ]
