# Generated by Django 4.0.4 on 2022-05-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='url',
            field=models.URLField(blank=True, default='', max_length=50, null=True),
        ),
    ]
