# Generated by Django 4.0.4 on 2022-05-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_laboratorio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
