# Generated by Django 4.0.4 on 2022-05-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_laboratorio_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='professoresPraticas',
            field=models.ManyToManyField(blank=True, null=True, related_name='praticas', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='professoresTeoricas',
            field=models.ManyToManyField(blank=True, null=True, related_name='teoricas', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.projeto'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='topicos',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkedin',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pagina',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linguagem',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.linguagem'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
