# Generated by Django 4.0.4 on 2022-05-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_cadeira_ects_alter_cadeira_anoletivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
