# Generated by Django 4.0.4 on 2022-05-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_cadeira_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
