# Generated by Django 4.0.4 on 2022-05-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_pessoa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='data_de_ingresso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='data_de_termino',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
