# Generated by Django 4.0.4 on 2022-05-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_escola_data_de_ingresso_escola_data_de_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, null=True, related_name='projetos', to='portfolio.projeto'),
        ),
    ]
