# Generated by Django 4.0.4 on 2022-05-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_projeto_participantes_alter_cadeira_projetos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('link', models.URLField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='professoresPraticas',
            field=models.ManyToManyField(blank=True, related_name='praticas', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='professoresTeoricas',
            field=models.ManyToManyField(blank=True, related_name='teoricas', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linguagem',
            field=models.ManyToManyField(blank=True, to='portfolio.linguagem'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='portfolio.pessoa'),
        ),
    ]
