# Generated by Django 4.0.4 on 2022-05-28 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_post_alter_cadeira_professorespraticas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 4, 33, 27, 821422)),
        ),
    ]
