# Generated by Django 4.0.4 on 2022-05-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_alter_post_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data',
        ),
    ]
