# Generated by Django 4.0.4 on 2022-05-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_remove_post_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
