# Generated by Django 4.0.4 on 2022-05-28 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_alter_post_data_alter_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 5, 49, 24, 18860)),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='./portfolio/media/images/'),
        ),
    ]
