# Generated by Django 4.0.4 on 2022-05-28 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_alter_post_data_alter_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 23, 40, 4, 256414)),
        ),
    ]
