# Generated by Django 4.0.4 on 2022-05-28 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0048_alter_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontuacaoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pontuacao', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 0, 9, 26, 377908)),
        ),
    ]
