# Generated by Django 4.0.4 on 2022-05-28 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0051_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 0, 48, 24, 776349)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='pessoas', to='portfolio.pessoa'),
        ),
    ]
