# Generated by Django 4.0.4 on 2022-05-29 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0052_alter_post_data_alter_projeto_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='acronimo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='ano_de_criacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='criador',
            field=models.ManyToManyField(related_name='creator', to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='site_oficial',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 1, 8, 42, 171699)),
        ),
    ]
