# Generated by Django 4.0.4 on 2022-05-29 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_alter_post_data_alter_projeto_linguagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 1, 54, 55, 753691)),
        ),
    ]
