# Generated by Django 4.0.4 on 2022-05-29 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0057_aptidao_certificado_habilitacao_hobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptidao',
            name='disciplinas',
            field=models.ManyToManyField(related_name='cadeiras', to='portfolio.cadeira'),
        ),
        migrations.AddField(
            model_name='aptidao',
            name='projetos',
            field=models.ManyToManyField(related_name='projeto', to='portfolio.projeto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 4, 17, 45, 297327)),
        ),
    ]
