# Generated by Django 4.0.4 on 2022-05-29 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0058_aptidao_disciplinas_aptidao_projetos_alter_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptidao',
            name='tipo',
            field=models.CharField(choices=[('Tecnica', 'Tecnica'), ('Organizativa', 'Organizativa'), ('Linguagem Programação', 'Linguagem Programação'), ('Social', 'Social'), ('Linguistica', 'Linguistica')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 4, 20, 3, 91545)),
        ),
    ]
